// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

/**
 * Prisma CLI（migrate / db / studio / seed）専用の設定。
 *
 * アプリ実行時の接続はここではなく `src/lib/prisma.ts` の
 * ドライバアダプタ（@prisma/adapter-pg）が `DATABASE_URL` から張る。
 *
 * `datasource.url` に `DIRECT_URL` を優先して渡している理由:
 * Prisma 7 の `PrismaConfig` 型（node_modules/@prisma/config/dist/index.d.ts）の
 * `Datasource` は `url` と `shadowDatabaseUrl` の2つしか持たず、
 * Prisma 5/6 にあった `directUrl` 相当の項目は存在しない。
 * マイグレーションを実行する schema engine は
 * アドバイザリロックや DDL のために非プール接続を必要とするため、
 * CLI 側の url そのものを Neon の直接接続（DIRECT_URL）にする。
 *
 * `migrations.seed` は持たない。公開版の初期データは全体ではなく利用者ごとに
 * ユーザー作成時に投入する（src/lib/users.ts の createUserWithPresets。docs/steps/pub-1.md 設計判断 8）。
 */
const cliDatabaseUrl = process.env["DIRECT_URL"] ?? process.env["DATABASE_URL"];

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: cliDatabaseUrl,
  },
});
